### ISSUE TITLE
Improve server creation in new project wizard

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#11]
Currently, the `AEM Sample Multi-Module Project` wizard asks for many details concerning the server as opposed to the `New Server` wizard.

We should pre-fill the values in the project creation wizard with following default values:
* Server name: Adobe Experience Manager at localhost
* Host name: localhost
* Port: 4502
* Username: admin
* Password: admin
* Debug Port: 30303

**Comment by rombert** [comment]
Commit referenced incorrect issue, reopening
