### ISSUE TITLE
The TagExtraInfo class for "cq:defineObjects" (com.day.cq.wcm.tags.DefineObjectsTEI) could  	 not be instantiated

### ISSUE THREAD

**Issue by SBPrakash** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#29]
I am facing this issue in global.jsp.. pls help me... "on hovering <cq:defineObjects/> and <sling:defineObjects/>" I am getting this error.
Attached the screenshot.
![screen shot 2015-01-08 at 15 13 28](https://cloud.githubusercontent.com/assets/9323430/5660704/5b363004-9749-11e4-81de-8e79a6739534.png)

**Comment by justinedelson** [comment]
There's a few different problems which can cause this and it really isn't related to the AEM Eclipse Developer Tools.

* The original Uber Jar for AEM 6.0 didn't have tld files.
* The Uber Jar for AEM 6.0 and 6.1 (which do have tlds) have obsfucated class files which can't be instantiated. Since Eclipse's JSP support require instantiating the TagExtraInfo class, this fails.

A solution which works most of the time for me is to include dependency entries for the Sling and CQ taglibs directly and be sure to include them in the pom.xml file *before* the uber jar.

**Comment by patricklwy14** [comment]
Hi justinedelson, didn't quite get what you trying to explain. I did include both Sling and CQ taglibs in my xxx.ui.apps module's dependency, and I still have the same issue. Here's my dependency:

![1 jun 2015 12 34 19 am](https://cloud.githubusercontent.com/assets/7502803/7902766/05fbe808-07f7-11e5-853d-6944dfb16b5f.png)

**Comment by justinedelson** [comment]
Try moving those two dependencies *above* the AEM API dependency. That works for me, although not 100% of the time for reasons I've yet to figure out.

**Comment by patricklwy14** [comment]
Thanks for the prompt response. After applied the sequence you mentioned, I tried clean the project, close and reopen, restart Eclipse...still NO LUCK. I guess I'll just leave it alone for the time being. Thanks for the help anyway.

**Comment by cmrockwell** [comment]
I have the same problem after upgrading to 6.1 using the obfuscated uber jar and the taglibs shown above. I know this isn't a AEM Eclipse Dev Tools issue per se. We use Sightly, but still would like JSP support in eclipse. It would be really great if this plugin had a solution for JSP's in the IDE, or maybe example of Maven settings required for it.

**Comment by jbaix** [comment]
I solved the issue (in AEM61) including the dependency:
<dependency>
<groupId>org.apache.sling</groupId>
<artifactId>org.apache.sling.scripting.jsp.taglib</artifactId>
<version>2.2.4</version>
<scope>provided</scope>
</dependency>

Thank you Justin! 
Regards

**Comment by cmrockwell** [comment]
Perfect! Updating org.apache.sling.scripting.jsp.taglib version to 2.2.4 worked for me.
Thanks

**Comment by rombert** [comment]
Thanks all for the comments. I've updated the AEM Developer Tools for Eclipse documentation - https://docs.adobe.com/content/docs/en/dev-tools/aem-eclipse.html#Enabling%20tag%20library%20autocompletion%20in%20JSP%20files .
