### ISSUE TITLE
Component Dialogs Deleted When Publishing Changes to .Java Files

### ISSUE THREAD

**Issue by tlwhit2** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#31]
1) Create New Project in Eclipse Dev Tools Using Maven Archetype 7.
2) Connect to Local AEM 6.0 SP1 with Content Project.
3) Run Maven Build once with autoInstallPackage to get whole project deployed.
4) Edit & save a .java file in a component in the ui.apps project with any syntax error ( and sometimes, even with no error).
5) Confirm that dialogs are missing from component on server.

**Comment by rombert** [comment]
@tlwhit2  - thanks for the report. I _think_ this is actually [SLING-4098- Full coverage aggregates nested under a partial coverage aggregate incorrectly deleted when a sibling resource is published](https://issues.apache.org/jira/browse/SLING-4098) .

Can you try a trunk build of the Sling IDE Tooling to validate that it indeed fixes your bug? Please follow the instructions from [Sling IDE Tooling - building from source](https://sling.apache.org/documentation/development/ide-tooling.html#building-from-source).

**Comment by tlwhit2** [comment]
Hmm. Can't seem to get sling source to build:

**Comment by rombert** [comment]
What maven command did you use? Also, it seems that Tycho skips compilation, probably finds the classes as compiled by Eclipse.

You should run `mvn clean package` to be on the safe side.

**Comment by tlwhit2** [comment]
Just checking in to see if we have a feel for when this fix might be released. Thanks!

**Comment by rombert** [comment]
We should be able to release a new version by the end of February, but right now I can't make any hard promises.

**Comment by rombert** [comment]
Closing since this is fixed in the Sling IDE Tooling and will be incorporated in the next release
