### ISSUE TITLE
JCR_ROOT Path Breaks Upon Project Import

### ISSUE THREAD

**Issue by tlwhit2** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#32]
1) Create AEM project using Developer Tools for Eclipse, Maven Archetype 7.
2) Delete project from Eclipse, but do not delete contents on disk.
3) File->Import->Maven->Existing Maven Projects, select the project you created in step 1.
4) Look at 'problems' tab, and note that jcr_root is not correct.
5) Look at ui.apps project properties, note that path under 'AEM' tab is not correct (only has jcr_root).
6) Uncheck 'Content Project' facet in project properties.
7) Rick click on ui.apps, Configure->Convert To...Content Project.
8) Check Problems & 'AEM' tab, note that path is now set correctly.

**Comment by rombert** [comment]
Yup, it's a bit awkward now to set up. Also tracked in [SLING-3766 - Store the project's content sync root property in the filesystem](https://issues.apache.org/jira/browse/SLING-3766)

**Comment by rombert** [comment]
This issue has been fixed in the Sling IDE Tooling project ( see [SLING-3766:Store the project's content sync root property in the filesystem](https://issues.apache.org/jira/browse/SLING-3766) ) and will be incorporated in the next AEM Developer Tools public release.
