### ISSUE TITLE
how to unpublish without republishing

### ISSUE THREAD

**Issue by saulovenancio** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#35]
Hi, 
i am trying to remove all published content from the JCR, but there is just a button to clean and republish.
isnt there one for clean only the once published from JCR?
Thanks.

**Comment by rombert** [comment]
For the moment this isn't possible, but I'll keep it as an enhancement request

**Comment by rombert** [comment]
@saulovenancio - did you close this because you don't find it important anymore? I kept it open to consider for future releases
