### ISSUE TITLE
Setup Travis build

### ISSUE THREAD

**Issue by rombert** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#38]
@gabrielwalt - can you please enable the Travis build for this repo and for the aem-project-archetype? See http://docs.travis-ci.com/user/getting-started/ for details. Once the webhook is activated, I can take care of the rest.

Thanks!

**Comment by rombert** [comment]
@Adobe-Marketing-Cloud/owners - can one of you please enable the Travis build hook for aem-eclipse-developer-tools and aem-project-archetype?

Thanks

**Comment by acollign** [comment]
I can certainly do that. Lets coordinate offline.

**Comment by rombert** [comment]
Great, thanks @acollign

**Comment by rombert** [comment]
Fixed, thanks a lot for your help
