### ISSUE TITLE
New project should offer option to use already existing folder.

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#45]
When creating a new project and a corresponding folder already exists, then it fails without any useful help message. Instead, it should offer the option to overwrite that folder.

**Comment by rombert** [comment]
Reusing an existing folder is tricky - what if there is already data in there? It means that we either delete the existing data or merge the old and the new, neither of which is acceptable IMO.

Instead, the wizard warns that 'A project with the name $name already exists' and does not allow the user to proceed to the next step - done for #8 .

I'm going to close this as a WONTFIX, please reopen if you have an idea of how to reuse an existing folder.
