### ISSUE TITLE
Syncing favicons seems to corrupt them

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#46]
Steps to reproduce:
* Create a new project using the archetype
* Sync it to an AEM instance
* The favicon is now corrupted:
  /etc/designs/${appsFolderName}/favicon.ico

**Comment by rombert** [comment]
I'm unable to reproduce this, I verified in the following way:

1. Create sample project ( archetype version 11-snapshot )

Check sha1sum for the favicon: a0a8733a15b85813411087035d4bd477371059ee

2. Create AEM server in Eclipse
3. Connect to AEM server in Eclipse
4. Deploy .apps project to server from Eclipse

Check sha1sum for the favicon: a0a8733a15b85813411087035d4bd477371059ee

4. Go to the .apps project, navigate to /etc/designs/test, import from Server, 

Check sha1sum for the favicon: a0a8733a15b85813411087035d4bd477371059ee

So neither import nor export seem to corrupt the favicon. If you have more detailed steps to reproduce or can show me how it happens :-) please reopen
