### ISSUE TITLE
Unable to deploy latest bundle changes to Author

### ISSUE THREAD

**Issue by patricklwy14** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#48]
From the main project directory, run cmd = mvn clean install -PautoInstallBundle for the first time. Bundle deploy successfully. 

Do some changes like add new classes, new methods in existing class and update the version in package-info.java. Run the same command again and it indicate BUILD SUCCESS from the command prompt. 

**What's observed:**
1. The JAR under /apps/project/install should be the latest one, based on its jcr:content, jcr:lastModified date time value.
2. The bundle installed (found under localhost:4502/system/console/bundles) is not the latest one
* based on the exported Packages version. It do not reflect the new version number. 
* JSP that call to the new classes or methods reporting undefined error (can't find those class or method)

Using JDK 1.7.0_75, with Maven 3.2.5 in OSX Yosemite.

**Comment by rombert** [comment]
@patricklwy14 - it's not clear to me from your report, but are you using the AEM developer tools for Eclipse when deploying?

**Comment by patricklwy14** [comment]
I'm using eclipse luna JEE version, having AEM Dev Tools 1.0.4 plugin installed for development.
I then use my Terminal command prompt to run the maven command (mvn clean install -PautoInstallBundle) to deploy.

**Comment by rombert** [comment]
Right, but do you deploy using the AEM Dev Tools?

**Comment by patricklwy14** [comment]
I guess nope...cause essentially it's only maven command, right?

**Comment by patricklwy14** [comment]
I chance upon some forum mentioning that if the bundle version is the same, it won't get updated unless the version number ended with -SNAPSHOT. Could it be the root cause here?

**Comment by rombert** [comment]
> I chance upon some forum mentioning that if the bundle version is the same, it won't get updated unless the version number ended with -SNAPSHOT

That's right, please use -SNAPSHOT for your Maven artifact version.

**Comment by patricklwy14** [comment]
Arggss..!!! OSGI Bundle...! Thanks for the prompt response guys!

**Comment by rombert** [comment]
Cool, happy to help
