### ISSUE TITLE
ClassNotFoundException: org.apache.jackrabbit.jcr2spi.Jcr2spiRepositoryFactory error when trying to start AEM server in eclipse

### ISSUE THREAD

**Issue by rajeevy69** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#55]
@All, I am getting below error when trying to start my AEM server An internal error occurred during: "Starting Adobe Experience Manager at localhost".
java.lang.ClassNotFoundException: org.apache.jackrabbit.jcr2spi.Jcr2spiRepositoryFactory

Any help is really appreciated.

**Comment by rombert** [comment]
@rajeevy69  - you already posted in #28 so let's keep the discussion there
