### ISSUE TITLE
Can you explain Install section of Server config

### ISSUE THREAD

**Issue by munkeyjooce** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#59]
In the Install "Specify how to install bundles on the server", it would be good if you can explain the differences between "Install bundles via bundle upload" and "Install bundles directly from the filesystem" - which one do you use when and how does it affect the server connection.

I have looked on the Sling IDE Tooling page and there is nothing specific there either.

**Comment by eglistefan** [comment]
Thx for reporting, @munkeyjooce, I've now added an explanation in rev 1714784 - the public docu site should be updated with this change soon.

**Comment by rombert** [comment]
FTR, the changes that @eglistefan mentioned are live at https://sling.apache.org/documentation/development/ide-tooling.html#server-configuration .

I consider this fixed, please reopen if you need more details.

**Comment by munkeyjooce** [comment]
Thanks! Much appreciated.
