### ISSUE TITLE
AEM Javadocs 

### ISSUE THREAD

**Issue by cmrockwell** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#61]
I'm using AEM 6.1, but Javadocs don't seem to work in Eclipse. I'm looking for advice relating to this SO question.   http://stackoverflow.com/questions/25820428/how-to-configure-javadocs-for-aem-cq5-6

It seems Javadocs are available..
https://repo.adobe.com/nexus/content/groups/public/com/adobe/aem/uber-jar/6.1.0/

According to the link below there should not be a need to explicitly add the JavaDocs. unfortunately it's not working for me...
http://stackoverflow.com/questions/17496996/maven-dependency-with-javadocs

**Comment by eglistefan** [comment]
Besides http://stackoverflow.com/questions/44396/how-to-reference-javadocs-to-dependencies-in-mavens-eclipse-plugin-when-javadoc , have you also tried configuring the javadoc jar in eclipse (in the Project Explorer, open 'Maven Dependencies' and right-click on the jar you want to attach it to)?

**Comment by rombert** [comment]
@cmrockwell - I am not sure what is going wrong here. The AEM plugin does not in any way try to influence javadoc resolution, so it's all Maven/m2e here.

I would suggest the following steps:

1) Right-click the aem-api jar ( or equivalent for 6.1 ) and click on Maven and then on Download JavaDoc

![m2e-download-javadoc](https://cloud.githubusercontent.com/assets/21237/13048498/eaf3f78e-d3ee-11e5-95b0-793e27b25355.png)

2) If that does not work, open a terminal and run the following command in the working directory of the project referencing the AEM api/uber har:

    $ mvn dependency:resolve -Dclassifier=javadoc

My intuition is that _maybe_ m2e does not resolve javadocs from repositories defined in the pom.xml file, but that's a long shot.

**Comment by cmrockwell** [comment]
Thanks a lot! very useful
