### ISSUE TITLE
New project wizard doesn't lists all archetypes for project creation

### ISSUE THREAD

**Issue by sandeepkumar03** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#70]
When creating a new project, the plugin is listing only archetypes with group `<groupId>com.adobe.granite.archetypes</groupId>` from the [archetypes list](https://repo.adobe.com/nexus/content/groups/public/archetype-catalog.xml)  

The other archetypes of `<groupId>com.day.jcr.vault</groupId>` are not listed. Is this as per design?

**Comment by eglistefan** [comment]
@sandeepkumar03 , yes, we explicitly [filter](https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/blob/0ead054a2c879bdfc99899d80072f0367548750d/com.adobe.granite.ide.eclipse-ui/src/main/java/com/adobe/granite/ide/eclipse/ui/wizards/np/NewGraniteProjectWizard.java#L58) for that groupId as the wizard can only handle those archetypes atm.

**Comment by sandeepkumar03** [comment]
okay great. Thanks @eglistefan
