### ISSUE TITLE
Core module in not getting added to server

### ISSUE THREAD

**Issue by salman18j** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#73]
Hi,

I am using aem eclipse plugin in Eclipse Mars 2 on Mac OX. I am not getting option to add core module to AEM server. It is working on Windows version of Eclispe

Regards,
Salman

**Comment by midnit** [comment]
Ditto... Created project from AEM perspective, didn't setup server on project creation due to Issue #67, so setup server after the fact, updated tomcat ports, right click to "Add and Remove..." and only seeing "project.ui.apps" and "project.ui.content"

**Comment by midnit** [comment]
Thanks to @auniverseaway, you should check the diff between your bundle pom and a [vanilla bundle pom from Archetype10](https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/master/src/main/archetype/core/pom.xml)... For me, I was missing the following in the <build><plugins> section:

```
<plugin>		
    <groupId>org.apache.sling</groupId>		
    <artifactId>maven-sling-plugin</artifactId>		
</plugin>
```

**Comment by salman18j** [comment]
Thanks @midnit, I was also missing the same entry.

**Comment by rombert** [comment]
Looks like there's nothing more to do here, please reopen if needed.
