### ISSUE TITLE
AEM-Eclipse plugin is not able to recognize the archetype11 projects.?

### ISSUE THREAD

**Issue by pnvardhan** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#77]
Why AEM archetype11 projects are not able to show in Add resources when i try to add in AEM Server in Eclipse Neon for the Sync.
![image](https://cloud.githubusercontent.com/assets/28104826/25488089/f8e7b0ea-2b1a-11e7-9c33-bd1d6663dfbf.png)

And if i have only the projects open in Eclipse Neon that have been created by archetype11 (and all other aem archetype10 projects closed) then i can see a popup as shown below.

![image](https://cloud.githubusercontent.com/assets/28104826/25488108/05ae3bbe-2b1b-11e7-8e65-44533d0efacf.png)

**Comment by rombert** [comment]
Did you import just the root project or also all the sub-projects?

**Comment by pnvardhan** [comment]
Yes  have imported all sub-projects,
Even with brand new aem-project-archetype:11 imported project, it wont be able to show up. attaching the Document to reproduce the issue, comparing aem-project-archetype:11 vs aem-project-archetype:10 
[Eclipse Neon.docx](https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/files/980295/Eclipse.Neon.docx)

**Comment by rombert** [comment]
I just tested and it "works for me". Do you have any entries in the Eclipse error log?

**Comment by pnvardhan** [comment]
Yes, It gives the below Error.
[https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/SJXeVEhrpB5GXRgPwjkVTQVjTC9wxaSjP8PJ78ijODhsPyh92Q06BfxfgG6gqLlp](https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/SJXeVEhrpB5GXRgPwjkVTQVjTC9wxaSjP8PJ78ijODhsPyh92Q06BfxfgG6gqLlp)

**Comment by rombert** [comment]
This was an issue with the archetype, see #78
